package com.todor.diabetes;

public class ProductsArray {

    public static final String BACKER_PRODUCTS = "Хлебобулочные изделия";
    public static final String CANNED_FISH = "Рыбные консервы";
    public static final String ALCOHOL_DRINKS = "Алкогольные напитки";
    public static final String FRESH_FISH = "Рыба свежая, охлажденная, мороженная";
    public static final String FISH_PRODUCTS = "Рыбные продукты готовые";
    public static final String FRUITS_VEGETABLES = "Фрукты и овощи, ягоды свежие";
    public static final String COOKED_PRODUCTS = "Готовые блюда";
    public static final String FRESH_MEAT = "Мясо свежее";
    public static final String MEAT_PRODUCTS = "Мясопродукты готовые";
    public static final String MILK_PRODUCTS = "Молочные продукты";
    public static final String MUSHROOMS = "Грибы";
    public static final String NUTS = "ОРЕХИ";
    public static final String COOKED_VEGETABLES = "Овощи готовые";
    public static final String CEREALS_FLOUR_PASTA = "Крупы и зернобобовые, мука, макароны";
    public static final String SAUCE = "Соусы";
    public static final String DRIED_FRUITS = "Сухофрукты";

    public static String[][] getProductArray() {
        String[][] productsArray = new String[][]{
                {"Батон", "50.6", BACKER_PRODUCTS},
                {"Блины", "34.3", BACKER_PRODUCTS},
                {"Булка сдобная", "57.2", BACKER_PRODUCTS},
                {"Булочка из слоеного теста", "50.6", BACKER_PRODUCTS},
                {"Булочки Тирольские Щелково", "50.6", BACKER_PRODUCTS},
                {"Завитки слоеные с маком", "62.8", BACKER_PRODUCTS},
                {"Кекс", "45.1", BACKER_PRODUCTS},
                {"Крекер с сыром", "61.5", BACKER_PRODUCTS},
                {"Лепешка ржаная", "43.6", BACKER_PRODUCTS},
                {"Лепешка узбекская", "57.9", BACKER_PRODUCTS},
                {"Лепешки Ладушки пшеничные", "56.1", BACKER_PRODUCTS},
                {"Палочки сдобные", "66.9", BACKER_PRODUCTS},
                {"Печенье овсяное", "70.8", BACKER_PRODUCTS},
                {"Печенье с джемом", "52.7", BACKER_PRODUCTS},
                {"Пицца ветчина с сыром", "17.6", BACKER_PRODUCTS},
                {"Пицца Casa Nostra", "29.8", BACKER_PRODUCTS},
                {"Пряники мятные", "31.5", BACKER_PRODUCTS},
                {"Рулет", "67.1", BACKER_PRODUCTS},
                {"Сухарики белые", "67.0", BACKER_PRODUCTS},
                {"Сухарики черные", "71.0", BACKER_PRODUCTS},
                {"Тесто слоеное", "36.0", BACKER_PRODUCTS},
                {"Хлеб Богатырский", "21.8", BACKER_PRODUCTS},
                {"Хлеб Довольство с кориандр и солодом", "30.1", BACKER_PRODUCTS},
                {"Хлеб \"Спеккл\" длинный", "49.8", BACKER_PRODUCTS},
                {"Хлеб белый", "46.7", BACKER_PRODUCTS},

                {"Мидии в собс соку Аlax", "1.7", CANNED_FISH},
                {"Сельдь в соусе Херес", "20.0", CANNED_FISH},

                {"Мартини Бьянко", "17.0 ", ALCOHOL_DRINKS},
                {"Пиво Будвайзер", "3.0", ALCOHOL_DRINKS},
                {"Пиво Кромбахер", "2.2", ALCOHOL_DRINKS},
                {"Пиво Кроненбург", "4.6", ALCOHOL_DRINKS},
                {"Пиво Крушовицы", "4.4", ALCOHOL_DRINKS},
                {"Пиво Оболонь светлое", "3.3", ALCOHOL_DRINKS},
                {"Пиво Lowenbrau", "4.7", ALCOHOL_DRINKS},
                {"Пиво Tuborg", "4.6", ALCOHOL_DRINKS},
                {"Пиво Zipfer", "2.3", ALCOHOL_DRINKS},
                {"Пиво-Старопрамен", "3.5", ALCOHOL_DRINKS},
                {"Чинзано бьянко", "18.0", ALCOHOL_DRINKS},

                {"Морской окунь", "0.0", FRESH_FISH},
                {"Морской язык", "0.0", FRESH_FISH},
                {"Морской язык (2)", "0.0", FRESH_FISH},
                {"Сом", "0.0", FRESH_FISH},

                {"Крабовые палочки", "0.0", FISH_PRODUCTS},
                {"Креветки вареные", "0.0", FISH_PRODUCTS},
                {"Мидии заморож \"Бухта изоб\"", "3.3", FISH_PRODUCTS},
                {"Осетровый балык х/к", "0.0", FISH_PRODUCTS},
                {"Скумбрия х/к", "0.0", FISH_PRODUCTS},
                {"Соленая горбуша", "0.0", FISH_PRODUCTS},

                {"Авокадо", "5.0", FRUITS_VEGETABLES},
                {"Виноград (2)", "15.0", FRUITS_VEGETABLES},
                {"Груши Нэши", "7.1", FRUITS_VEGETABLES},
                {"Крапива ранняя", "5.0", FRUITS_VEGETABLES},
                {"Маслины Бондюэль с косточкой", "6.3", FRUITS_VEGETABLES},
                {"Пастернак (корень)", "8.5", FRUITS_VEGETABLES},
                {"Свити (примерно)", "10.0", FRUITS_VEGETABLES},
                {"Хурма", "15.8", FRUITS_VEGETABLES},
                {"Хурма (2)", "13.5", FRUITS_VEGETABLES},

                {"Борщ московский зам 4 сезона 400", "8.9", COOKED_PRODUCTS},
                {"Картофель жареный", "16.4", COOKED_PRODUCTS},
                {"Салат мясной", "4.7", COOKED_PRODUCTS},
                {"Салат овощной со сметаной", "3.5", COOKED_PRODUCTS},
                {"Салат оливье", "6.7", COOKED_PRODUCTS},
                {"Сельдь под шубой Диланес", "4.8", COOKED_PRODUCTS},
                {"Сельдь филе под шубой Перекресток", "4.8", COOKED_PRODUCTS},
                {"Сырники творожные", "14.6", COOKED_PRODUCTS},
                {"Сырники", "14.8", COOKED_PRODUCTS},
                {"Творожная масса с вареньем", "76.9", COOKED_PRODUCTS},
                {"Фасоль с сыром и криветками", "10.7", COOKED_PRODUCTS},

                {"Индюшатина", "0.0", FRESH_MEAT},
                {"Косули мясо", "0.0", FRESH_MEAT},
                {"Кролик", "0.0", FRESH_MEAT},
                {"Куриная печень", "1.6", FRESH_MEAT},
                {"Куриное сердце", "0.8", FRESH_MEAT},
                {"Куриный желудок", "0.6", FRESH_MEAT},
                {"Сайгака мясо", "0.0", FRESH_MEAT},
                {"Свинина нежирная", "0.0", FRESH_MEAT},
                {"Яка мясо", "0.0", FRESH_MEAT},

                {"Баранина в казане", "0.0", MEAT_PRODUCTS},
                {"Ветчина для завтрака Рублево", "0.0", MEAT_PRODUCTS},
                {"Ветчина свиная", "0.0", MEAT_PRODUCTS},
                {"Кобаски охотничьи", "0.0", MEAT_PRODUCTS},
                {"Колбаса Брауншвейг сервелат ЧМПЗ", "0.0", MEAT_PRODUCTS},
                {"Колбаса Брауншвейгская с/к Рублево", "0.8", MEAT_PRODUCTS},
                {"Колбаса Докторская Рублево", "0.0", MEAT_PRODUCTS},
                {"Колбаса Докторская Рублево в нат оболочке (В/с)", "0.0", MEAT_PRODUCTS},
                {"Колбаса Миланская", "0.0", MEAT_PRODUCTS},
                {"Колбаса  в/к сервелат Рублевский Деликатесный", "0.0", MEAT_PRODUCTS},
                {"Колбаса Салями-сервелат Кампомос", "0.0", MEAT_PRODUCTS},
                {"Колбаса Украинская", "0.0", MEAT_PRODUCTS},
                {"Колбаса вар.-копч.- сервелат", "0.0", MEAT_PRODUCTS},
                {"Колбаса варено-копченая Имперская", "0.0", MEAT_PRODUCTS},
                {"Колбаса докторская", "0.0", MEAT_PRODUCTS},
                {"Колбаса еврейская (рублево)", "0.0", MEAT_PRODUCTS},
                {"Колбаса зернистая Клинская", "0.0", MEAT_PRODUCTS},
                {"Колбаса краковская", "0.0", MEAT_PRODUCTS},
                {"Колбаса кровяная", "3.0", MEAT_PRODUCTS},
                {"Колбаса любительская", "0.0", MEAT_PRODUCTS},
                {"Колбаса московская с/к", "0.0", MEAT_PRODUCTS},
                {"Колбаса с/к Мадера Рублево", "0.0", MEAT_PRODUCTS},
                {"Колбаса с/к Московская Царицино", "0.0", MEAT_PRODUCTS},
                {"Колбаса с/к Салями Елисеевская Рублево", "0.0", MEAT_PRODUCTS},
                {"Колбаса свиная с/к Рублево", "0.0", MEAT_PRODUCTS},
                {"Колбаса сервелат", "0.0", MEAT_PRODUCTS},
                {"Колбаса сервелат \"Рублевский гурман\" в/к в/с Рублево", "0.0", MEAT_PRODUCTS},
                {"Колбаса сервелат Финский Подольск", "0.0", MEAT_PRODUCTS},
                {"Колбаса-Сервелат в/к Рублево", "0.0", MEAT_PRODUCTS},
                {"Копченая корейка свиная", "0.0", MEAT_PRODUCTS},
                {"Котлета ложкарев", "6.5", MEAT_PRODUCTS},
                {"Котлеты куриные", "9.8", MEAT_PRODUCTS},
                {"Котлеты отбивные (R)", "10.7", MEAT_PRODUCTS},
                {"Купаты Мортадель", "0.0", MEAT_PRODUCTS},
                {"Курица в подливе", "4.4", MEAT_PRODUCTS},
                {"Курица под аджикой", "1.5", MEAT_PRODUCTS},
                {"Мясо жаренное-свинина нежирная", "0.0", MEAT_PRODUCTS},
                {"Окорочка жареные", "0.0", MEAT_PRODUCTS},
                {"Паштет печеночный Черкизово", "2.0", MEAT_PRODUCTS},
                {"Печень жареная с луком (R)", "3.9", MEAT_PRODUCTS},
                {"Печень с молоком", "7.0", MEAT_PRODUCTS},
                {"Поджарка из говядины (R)", "4.9", MEAT_PRODUCTS},
                {"Птичье мясо с луком", "1.8", MEAT_PRODUCTS},
                {"Ромштекс (R)", "11.1", MEAT_PRODUCTS},
                {"Сардельки Рублевские свиные-люкс", "0.0", MEAT_PRODUCTS},
                {"Свиная грудинка копченая", "0.0", MEAT_PRODUCTS},
                {"Свиная отбивная", "4.8", MEAT_PRODUCTS},
                {"Свинина вареная", "0.0", MEAT_PRODUCTS},
                {"Свиной шпик", "0.0", MEAT_PRODUCTS},
                {"Сосиски Венские Рублево", "0.0", MEAT_PRODUCTS},
                {"Студень", "0.8", MEAT_PRODUCTS},
                {"Тефтели", "11.6", MEAT_PRODUCTS},

                {"Брынза Болгарская", "11.6", MILK_PRODUCTS},
                {"Брынза Feta", "6.5", MILK_PRODUCTS},
                {"Брынза Fetaki", "11.6", MILK_PRODUCTS},
                {"Йогурт 1.5%", "11.6", MILK_PRODUCTS},
                {"Йогурт Campina", "18.0", MILK_PRODUCTS},
                {"Кефир Агуша бифи", "3.7", MILK_PRODUCTS},
                {"Кефир Био 1.5% Троицкий Околица", "3.9", MILK_PRODUCTS},
                {"Кефир Био-мах 3.2%", "4.0", MILK_PRODUCTS},
                {"Кефир ДВД 1%", "4.0", MILK_PRODUCTS},
                {"Кефир ДВД 3.2%", "4.0", MILK_PRODUCTS},
                {"Кефир Докт Бифи", "4.0", MILK_PRODUCTS},
                {"Кефир 33 коровы", "4.0", MILK_PRODUCTS},
                {"Молоко 2.5%", "4.5", MILK_PRODUCTS},
                {"Молоко 3.2% Околица пастериз", "4.7", MILK_PRODUCTS},
                {"Молоко 6% Вкуснотеево", "4.7", MILK_PRODUCTS},
                {"Молоко пастериз 3.2%", "4.7", MILK_PRODUCTS},
                {"Молоко топленое Владимир", "4.7", MILK_PRODUCTS},
                {"Молочный коктейль", "9.5", MILK_PRODUCTS},
                {"Мороженное Русский размер", "20.9", MILK_PRODUCTS},
                {"Мороженное Торжество", "26.9", MILK_PRODUCTS},
                {"Мороженное Торжество пломбир", "20.4", MILK_PRODUCTS},
                {"Мороженное Эскимо", "4.7", MILK_PRODUCTS},
                {"Мороженное пломбир в шоколаде", "14.0", MILK_PRODUCTS},
                {"Мороженное помбир ванильный Метелица", "21.6", MILK_PRODUCTS},
                {"Мороженное торт Венеция", "19.3", MILK_PRODUCTS},
                {"Мороженное Nestle 48 коп", "20.6", MILK_PRODUCTS},
                {"Мороженное-пломбир Чистая Линия", "20.4", MILK_PRODUCTS},
                {"Мороженое \"Гигант\"", "32.6", MILK_PRODUCTS},
                {"Мороженое молочное", "26.6", MILK_PRODUCTS},
                {"Мороженое пломбир", "17.5", MILK_PRODUCTS},
                {"Мороженое сливочное", "23.4", MILK_PRODUCTS},
                {"Сметана Дом В Дер 25%", "3.2", MILK_PRODUCTS},
                {"Сметана Милая Мила 15%", "3.6", MILK_PRODUCTS},
                {"Сметана Милая Мила 25%", "3.2", MILK_PRODUCTS},
                {"Сметана Петмол-Простоквашино 15%", "3.0", MILK_PRODUCTS},
                {"Сметана \"Пастушок\" 10%", "4.0", MILK_PRODUCTS},
                {"Сметана 18% Молочная традиция", "3.7", MILK_PRODUCTS},
                {"Сметана 18% Савушкин продукт", "3.7", MILK_PRODUCTS},
                {"Сметана 20% Красная", "3.7", MILK_PRODUCTS},
                {"Сметана 20% Останкинская", "3.2", MILK_PRODUCTS},
                {"Сметана 20% 33 коровы", "3.2", MILK_PRODUCTS},
                {"Сметана 20% домашняя Янино", " 3.2", MILK_PRODUCTS},
                {"Сметана 25% 33 коровы", "2.7", MILK_PRODUCTS},
                {"Сметана 25% 33 коровы нов", "3.2", MILK_PRODUCTS},
                {"Сметана 30% останкинская", "3.0", MILK_PRODUCTS},
                {"Сметана класс Ромашкино 20%", "3.2", MILK_PRODUCTS},
                {"Сметана Valio домашняя 23%", "3.1", MILK_PRODUCTS},
                {"Сыр Адыгейский", "0.0", MILK_PRODUCTS},
                {"Сыр Гауда жирность 48%", "0.0", MILK_PRODUCTS},
                {"Сыр Звенигородский", "0.0", MILK_PRODUCTS},
                {"Сыр Ольтермани", "0.0", MILK_PRODUCTS},
                {"Сыр Ольтермани 29%", "0.0", MILK_PRODUCTS},
                {"Сыр Ольтермани 55%", "0.0", MILK_PRODUCTS},
                {"Сыр Рокфор", "3.2", MILK_PRODUCTS},
                {"Сыр Советский", "0.0", MILK_PRODUCTS},
                {"Сыр Тильзитер", "0.0", MILK_PRODUCTS},
                {"Сыр голландский", "0.0", MILK_PRODUCTS},
                {"Сыр колбасный копченый", "0.0", MILK_PRODUCTS},
                {"Сыр плавлавленный Prezident маасдам", "6.5", MILK_PRODUCTS},
                {"Сыр плавленный", "0.0", MILK_PRODUCTS},
                {"Сыр российский", "0.0", MILK_PRODUCTS},
                {"Сыр швейцарский", "0.4", MILK_PRODUCTS},
                {"Сырники из творога", "19.6", MILK_PRODUCTS},
                {"Сырок ванильный", "24.5", MILK_PRODUCTS},
                {"Сырок творожный", "11.6", MILK_PRODUCTS},
                {"Сырок творожный глазированный", "33.0", MILK_PRODUCTS},
                {"Творог жирный", "1.3", MILK_PRODUCTS},
                {"Творог зерненый Простоквашино", "2.0", MILK_PRODUCTS},
                {"Творог нежирный", "1.8", MILK_PRODUCTS},
                {"Творожная запеканка (R)", "16.7", MILK_PRODUCTS},
                {"Творожная масса", "18.0", MILK_PRODUCTS},
                {"Творожок нежный 10% Кварк", "1.0", MILK_PRODUCTS},
                {"Творог жирный", "1.3", MILK_PRODUCTS},
                {"Творог жирный", "1.3", MILK_PRODUCTS},
                {"Творог жирный", "1.3", MILK_PRODUCTS},

                {"Рыжики по-корейски", "2.1", MUSHROOMS},
                {"Шампиньоны замороженные \"Витамин\"", "2.6", MUSHROOMS},
                {"Шампиньоны свежие", "0.1", MUSHROOMS},

                {"Арахис", "14.0", NUTS},
                {"Бразильский", "15.0", NUTS},
                {"Грецкие", "13.7", NUTS},
                {"Кедровый", "14.5", NUTS},
                {"Кешью (АН)", "23.0", NUTS},
                {"Миндаль жар", "0.1", NUTS},
                {"Фисташки Emarko", "14.0", NUTS},
                {"Фундук2", "11.4", NUTS},

                {"Бамия 4 сезона", "8.0", COOKED_VEGETABLES},
                {"Брусника замороженная 4 сезона", "8.2", COOKED_VEGETABLES},
                {"Гавайская смесь Витамин", "24.2", COOKED_VEGETABLES},
                {"Гавайская смесь \"Дом обед\" 400", "19.7", COOKED_VEGETABLES},
                {"Гавайская смесь 4 Сезона", "24.8", COOKED_VEGETABLES},
                {"Гювеч Пиканта", "3.5", COOKED_VEGETABLES},
                {"Гювеч 4 сезона 400", "5.2", COOKED_VEGETABLES},
                {"Кабачки жареные", "7.0", COOKED_VEGETABLES},
                {"Капуста квашенная Сударушка с клюквой", "3.3", COOKED_VEGETABLES},
                {"Картофель жареный", "16.4", COOKED_VEGETABLES},
                {"Картофель пюре", "14.3", COOKED_VEGETABLES},
                {"Картофель фри жареный", "26.6", COOKED_VEGETABLES},
                {"Картофельное пюре", "14.3", COOKED_VEGETABLES},
                {"Китайская смесь 4 Сезона", "3.9", COOKED_VEGETABLES},
                {"Клубника морожен 4 сезона", "6.6", COOKED_VEGETABLES},
                {"Кукуруза консервированная Микадо", "20.0", COOKED_VEGETABLES},
                {"Кукуруза Hortex 450", "19.3", COOKED_VEGETABLES},
                {"Кукурузные хлопья не глаз.", "34.0", COOKED_VEGETABLES},
                {"Лечо", "3.4", COOKED_VEGETABLES},
                {"Лечо Краски Лета 400", "3.0", COOKED_VEGETABLES},
                {"Лечо 4 сезона 400", "5.3", COOKED_VEGETABLES},
                {"Лечо по венгерски Витамин 400", "4.4", COOKED_VEGETABLES},
                {"Лечо Hortex 400", "3.4", COOKED_VEGETABLES},
                {"Маслины Iberica", "4.8", COOKED_VEGETABLES},
                {"Маслины Maestra de Oliva", "4.8", COOKED_VEGETABLES},
                {"Маслины SOL NEGRO", "4.0", COOKED_VEGETABLES},
                {"Мексиканская смесь Витамин", "7.5", COOKED_VEGETABLES},
                {"Морковь вареная", "7.0", COOKED_VEGETABLES},
                {"Овощная икра Балтимор", "8.0", COOKED_VEGETABLES},
                {"Овощная смесь сухая \"Венская\"", "47.5", COOKED_VEGETABLES},
                {"Огурцы консервир Хозяин", "3.0", COOKED_VEGETABLES},
                {"Огурцы марин немец", "1.5", COOKED_VEGETABLES},
                {"Огурцы марин EKO", "4.5", COOKED_VEGETABLES},
                {"Огурцы марин Family", "2.6", COOKED_VEGETABLES},
                {"Огурцы марин Gartenz", "3.8", COOKED_VEGETABLES},
                {"Огурцы маринов \"от души\"", "4.0", COOKED_VEGETABLES},
                {"Огурцы маринованные Алладин", "2.3", COOKED_VEGETABLES},
                {"Огурцы маринованные Балтимор", "4.0", COOKED_VEGETABLES},
                {"Огурцы маринованные Хозяин", "5.4", COOKED_VEGETABLES},
                {"Огурцы маринованные Хозяин остренькие", "3.5", COOKED_VEGETABLES},
                {"Огурцы маринованные конюшоны Бондюэль", "3.5", COOKED_VEGETABLES},
                {"Огурцы маринованные конюшоны немецкие", "7.0", COOKED_VEGETABLES},
                {"Огурцы маринованные с чесноком Green Ray", "5.0", COOKED_VEGETABLES},
                {"Огурцы маринованные GLOSTER", "2.4", COOKED_VEGETABLES},
                {"Огурцы соленые по-домашнему", "3.6", COOKED_VEGETABLES},
                {"Огурцы стерилиз Premium", "4.4", COOKED_VEGETABLES},
                {"Оливки ACORSA", "5.2", COOKED_VEGETABLES},
                {"Оливки Oroverde", "4.4", COOKED_VEGETABLES},
                {"Паприкаш 4 сезона", "4.4", COOKED_VEGETABLES},
                {"Патиссоны маринован 4 сезона", "4.0", COOKED_VEGETABLES},
                {"Патиссоны с огурцами марин 4 сезона", "5.0", COOKED_VEGETABLES},
                {"Перец Пеперони (Германия)", "6.3", COOKED_VEGETABLES},
                {"Перец пеперони Gartenc", "2.5", COOKED_VEGETABLES},
                {"Перец пеперони Parmen", "3.0", COOKED_VEGETABLES},
                {"Перец пеперони green ray", "1.3", COOKED_VEGETABLES},
                {"Перец сладкий нарезанный 4 сезона 400", "5.4", COOKED_VEGETABLES},
                {"Перец стрючков зелен маринов", "4.7", COOKED_VEGETABLES},
                {"Перец фаршированный", "5.6", COOKED_VEGETABLES},
                {"Помидоры маринованные", "1.8", COOKED_VEGETABLES},
                {"Помидоры соленые", "1.7", COOKED_VEGETABLES},
                {"Рагу морож 4 сезона", "3.8", COOKED_VEGETABLES},
                {"Рагу овощное Перекресток", "3.8", COOKED_VEGETABLES},
                {"Рагу овощное Hortex", "3.5", COOKED_VEGETABLES},
                {"Рататуй  Хортекс", "2.8", COOKED_VEGETABLES},
                {"Сакена с рисом 4 сезона 600", "13.9", COOKED_VEGETABLES},
                {"Смесь сушеных овощей КРАСНАЯ", "60.5", COOKED_VEGETABLES},
                {"Томаты в с/с Закусон", "3.9", COOKED_VEGETABLES},
                {"Томаты в с/с Коррадо", "6.1", COOKED_VEGETABLES},
                {"Томаты в собс/с Corrado", "6.1", COOKED_VEGETABLES},
                {"Томаты в собс/с EKO", "5.2", COOKED_VEGETABLES},
                {"Томаты марин Огородников", "5.0", COOKED_VEGETABLES},
                {"Томаты неочищ в с/с 4 сезона", "2.8", COOKED_VEGETABLES},
                {"Томаты неочищен Хозяин", "3.5", COOKED_VEGETABLES},
                {"Фасоль \"Пинто\" ЗВ 420", "15.0", COOKED_VEGETABLES},
                {"Фасоль белая в томат Daucy125", "12.2", COOKED_VEGETABLES},
                {"Фасоль белая в томат Daucy250", "2.8", COOKED_VEGETABLES},
                {"Фасоль белая консер Rosanna 400", "5.0", COOKED_VEGETABLES},
                {"Фасоль белая Daucy125", "15.4", COOKED_VEGETABLES},
                {"Фасоль белая daucy консер. 250", "15.4", COOKED_VEGETABLES},
                {"Фасоль в томат соу \"Хайнц\" 415", "13.1", COOKED_VEGETABLES},
                {"Фасоль в томат соу \"Хайнц\" 200", "13.1", COOKED_VEGETABLES},
                {"Фасоль 4 сезона", "3.1", COOKED_VEGETABLES},
                {"Фасоль красная Доси 250-360", "16.8", COOKED_VEGETABLES},
                {"Фасоль красная Daucy 125", "16.8", COOKED_VEGETABLES},
                {"Фасоль лоби 4 сезона 400", "3.1", COOKED_VEGETABLES},
                {"Фасоль плоскоплодная", "6.8", COOKED_VEGETABLES},
                {"Фасоль с баклажанами Верес", "25.0", COOKED_VEGETABLES},
                {"Фасоль с овощами Верес", "16.0", COOKED_VEGETABLES},
                {"Фасоль стручковая Daucy 225", "4.0", COOKED_VEGETABLES},
                {"Хлопья кукурузные глазированные", "74.1", COOKED_VEGETABLES},
                {"Черника 4 сезона", "8.2", COOKED_VEGETABLES},
                {"Чипсы", "52.0", COOKED_VEGETABLES},
                {"Яблоки печеные", "3.1", COOKED_VEGETABLES},
                {"Фасоль лоби 4 сезона 400", "14.5", COOKED_VEGETABLES},

                {"Крупа горох", "14.5", CEREALS_FLOUR_PASTA},
                {"Крупа горох колотый шлифованный", "44.0", CEREALS_FLOUR_PASTA},
                {"Крупа горох серый, сухой", "50.7", CEREALS_FLOUR_PASTA},
                {"Крупа горох сухой", "44.0", CEREALS_FLOUR_PASTA},
                {"Крупа горох сухой лущеный", "57.7", CEREALS_FLOUR_PASTA},
                {"Крупа гречневая", "68.0", CEREALS_FLOUR_PASTA},
                {"Крупа гречневая Агроальянс", "64.0", CEREALS_FLOUR_PASTA},
                {"Крупа гречневая Мистраль", "65.0", CEREALS_FLOUR_PASTA},
                {"Крупа гречневая \"Мария РА\"", "69.2", CEREALS_FLOUR_PASTA},
                {"Крупа гречневая \"Поваренок\"", "65.0", CEREALS_FLOUR_PASTA},
                {"Крупа гречневая ренц", "62.0", CEREALS_FLOUR_PASTA},
                {"Крупа кукурузная", "67.5", CEREALS_FLOUR_PASTA},
                {"Крупа манная", "73.3", CEREALS_FLOUR_PASTA},
                {"Крупа овсяная", "65.4", CEREALS_FLOUR_PASTA},
                {"Крупа перловая", "73.7", CEREALS_FLOUR_PASTA},
                {"Крупа пшенная", "69.3", CEREALS_FLOUR_PASTA},
                {"Крупа пшено Воложка", "66.5", CEREALS_FLOUR_PASTA},
                {"Крупа ржаная", "70.9", CEREALS_FLOUR_PASTA},
                {"Крупа рис", "77.3", CEREALS_FLOUR_PASTA},
                {"Крупа рис \"золотистый\"", "78.1", CEREALS_FLOUR_PASTA},
                {"Крупа рис бурый Агроальянс", "72.9", CEREALS_FLOUR_PASTA},
                {"Крупа рис длиннозерный \"Увелка\"", "70.7", CEREALS_FLOUR_PASTA},
                {"Крупа рис для японск кухни", "82.5", CEREALS_FLOUR_PASTA},
                {"Крупа рис коричневый мистраль", "72.0", CEREALS_FLOUR_PASTA},
                {"Крупа рис тайский пропар L рассыпчат", "82.5", CEREALS_FLOUR_PASTA},
                {"Крупа фасоль", "54.5", CEREALS_FLOUR_PASTA},
                {"Крупа фасоль Чистая крупа", "50.5", CEREALS_FLOUR_PASTA},
                {"Крупа фасоль 2", "47.0", CEREALS_FLOUR_PASTA},
                {"Крупа ячменная", "65.8", CEREALS_FLOUR_PASTA},
                {"Крупа ячневая", "71.7", CEREALS_FLOUR_PASTA},
                {"Крупа-чечевица Мистраль", "49.0", CEREALS_FLOUR_PASTA},
                {"Кукуруза для попкорна Волшебное дерево", "67.2", CEREALS_FLOUR_PASTA},
                {"Лапша домашняя (сухая)", "71.7", CEREALS_FLOUR_PASTA},
                {"Лапша одноразовая", "60.8", CEREALS_FLOUR_PASTA},
                {"Лапша сухая \"Ролтон\"", "70.0", CEREALS_FLOUR_PASTA},
                {"Макароны", "75.0", CEREALS_FLOUR_PASTA},
                {"Макароны спагетти \"Макфа\"", "71.5", CEREALS_FLOUR_PASTA},
                {"Макроны спагетти Италпаста 2мин", "72.0", CEREALS_FLOUR_PASTA},
                {"Мука кукурузная", "75.8", CEREALS_FLOUR_PASTA},
                {"Мука пшеничная \"Dobele\"", "70.0", CEREALS_FLOUR_PASTA},
                {"Мука пшеничная в/с", "74.2", CEREALS_FLOUR_PASTA},
                {"Мука пшеничная в/с Сокольническая", "70.0", CEREALS_FLOUR_PASTA},
                {"Мука пшеничная в/с Старооскольская", "68.9", CEREALS_FLOUR_PASTA},
                {"Пшеничная крупа", "71.3", CEREALS_FLOUR_PASTA},
                {"Сахар", "99.8", CEREALS_FLOUR_PASTA},
                {"Соя мясо Белсотек", "17.6", CEREALS_FLOUR_PASTA},
                {"Соя рубленная ветчина", "20.0", CEREALS_FLOUR_PASTA},
                {"Фруктоза", "99.9", CEREALS_FLOUR_PASTA},

                {"Аджика", "2.6", SAUCE},
                {"Аджика Верес", "12.0", SAUCE},
                {"Аджика острая 4 сезона", "11.0", SAUCE},
                {"Горчица", "15.2", SAUCE},
                {"Горчица МЖК", "14.5", SAUCE},
                {"Горчица баварская", "14.3", SAUCE},
                {"Горчица оригинальная с хреном Верес", "15.2", SAUCE},
                {"Горчица пряная с гр ор", "14.6", SAUCE},
                {"Горчица с хреном", "15.2", SAUCE},
                {"Кетчуп Акмалько Сацибели", "14.2", SAUCE},
                {"Кетчуп Балтимор - татарский", "23.7", SAUCE},
                {"Кетчуп Пикадор острый", "13.5", SAUCE},
                {"Кетчуп Пикадор острый -новый", "20.0", SAUCE},
                {"Кетчуп Пикадор острый с паприкой", "20.0", SAUCE},
                {"Кетчуп Пикадор томатный", "22.0", SAUCE},
                {"Кетчуп Пикадор шашлычный", "21.0", SAUCE},
                {"Кетчуп HEINZ острый", "23.2", SAUCE},
                {"Майонез Кальве Premium Quality", "3.3", SAUCE},
                {"Майонез МЖК Провансаль класс", "2.3", SAUCE},
                {"Майонез Рико на перепел яйцах", "3.7", SAUCE},
                {"Майонез \"Ладушка\"", "1.6", SAUCE},
                {"Майонез \"Магги\"", "3.4", SAUCE},
                {"Майонез\"Кальве\"", "5.0", SAUCE},
                {"Сацибели острый №13 Трест В", "4.7", SAUCE},
                {"Соус брын майон чеснок", "0.8", SAUCE},
                {"Соус майонез - чеснок", "4.0", SAUCE},
                {"Соус соевый \"Стебель бамбука\"", "20.0", SAUCE},
                {"Соус Heinz экзотический с ананас и имбирем", "34.0", SAUCE},
                {"Томатная паста", "19.0", SAUCE},

                {"Изюм", "66.0", DRIED_FRUITS},
                {"Инжир", "13.9", DRIED_FRUITS},
                {"Чернослив", "57.5", DRIED_FRUITS},

        };
        return productsArray;
    }

}
